// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-PsmB_ez7CGgOyp8wGWK-9qP5Pm6sgg',
    appId: '1:593850772780:web:8aa62f329a0673b18e5089',
    messagingSenderId: '593850772780',
    projectId: 'hearthealth-dsi',
    authDomain: 'hearthealth-dsi.firebaseapp.com',
    storageBucket: 'hearthealth-dsi.firebasestorage.app',
    measurementId: 'G-9SS42SBG34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNq204LS42QIAQvQtMrHcfhrKSzh62jU',
    appId: '1:593850772780:android:20fdb36dbc5809ad8e5089',
    messagingSenderId: '593850772780',
    projectId: 'hearthealth-dsi',
    storageBucket: 'hearthealth-dsi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn-PsmB_ez7CGgOyp8wGWK-9qP5Pm6sgg',
    appId: '1:593850772780:web:4ae2b2202c71b3498e5089',
    messagingSenderId: '593850772780',
    projectId: 'hearthealth-dsi',
    authDomain: 'hearthealth-dsi.firebaseapp.com',
    storageBucket: 'hearthealth-dsi.firebasestorage.app',
    measurementId: 'G-5LB1JRF8VJ',
  );
}